version: '3.1'

services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
