apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: bankly-scratchme-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bankly-scratchmems
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
        # type: AverageValue
        # averageValue: 25m
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
        # type: AverageValue
        # averageValue: 1024Mi